### ISSUE TITLE
CKAN produces unpredictable results if only part of a keyword is used as the search term

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#129]
CKAN does not return any results if only part of a keyword is used as the search term/phrase. To reproduce this behavior, open the Data page and search for "Number". The search returns 6 results. However, searches for "N", "Nu", "Numb", and "Numbe" return zero results when at least 6 results are expected.

Additionally,
Search for "Baseline" Returns 167 results as expected, but unlike the previous example, 
Search for "Baselin" (notice that the last letter ("e") is missing) also returns 167 results, and then
Search for "Baseli" (notice that the last two letters ("en") are missing) returns NO results

**Comment by cjhendrix** [comment]
More weird behavior:

https://data.hdx.rwlabs.org/search?q=norm (2 results, seems good)
https://data.hdx.rwlabs.org/search?q=normz (0 results, seems good)
https://data.hdx.rwlabs.org/search?q=normZ (373 results, doesn't make sense)

**Comment by danmihaila** [comment]
this will definitely need a nosetest that will have to test different scenarios.

**Comment by alexandru-m-g** [comment]
##### CKAN is using right now the **[DISMAX Query Parser](https://cwiki.apache.org/confluence/display/solr/The+DisMax+Query+Parser)**

Quoting from above page: `The q parameter does not support wildcard characters such as *`

I tested the search terms mentioned in this ticket and will try to go over each one below:

*  normZ - 365 results
  *  it actually splits this in 2 terms - so there are 2 documents that are found with a big relevance score and then there are alot more found with a small relevance score because of the "Z"   
  *  the solr schema xml uses a WordDelimiterFilterFactory with the following parameter **splitOnCaseChange="1"** 
*  baseli - 288 results 
  *  because stemming gives "base"
*  baselin  -  363 results
  *  it's actually the same as 'baseline' as the stemming of 'baseline' is 'baselin'
*  numbe  - 0 results
  * stemming gives 'numb'
*  Zimbabw - 5 results
  *  same as Zimbabwe because of stemming


##### Another option would be to use the **[EDISMAX Query Parser](https://cwiki.apache.org/confluence/display/solr/The+Extended+DisMax+Query+Parser)**

Quoting from above page: 
`supports the full Lucene query parser syntax` (including wildcards)

Also from http://wiki.apache.org/solr/ExtendedDisMax:
```
This parser supports full Lucene QueryParser syntax including 
boolean operators 'AND', 'OR', 
'NOT', '+' and '-', fielded search, term boosting, fuzzy, 
grouping with parens, phrase search, phrase
 slop, numeric ranges, wildcard search and more.
 If there is a syntax error in the input, such as 
non-existing field name or unbalanced double-quotes, 
the input is gracefully searched as literal 
strings.
```

Same search queries with EDISMAX:
*  normZ - 2 results
  *  the documents with low relevance score are no longer returned 
*  baseli - 281 results 
  *  baseli* - 363 results 
     *  stemming does NOT give 'base' anymore so results are similar/same as 'baselin'
*  baselin  -  363 results
  *  it's actually the same as 'baseline' as the stemming of 'baseline' is 'baselin'
*  numbe  - 0 results
  * numbe* - 314 results
*  Zimbabw - 5 results
  *  Zimbabw* - 5 results

Note: Useful online stemmer: http://snowball.tartarus.org/demo.php

**Comment by danmihaila** [comment]
@alexandru-m-g - excellent research.
@cjhendrix - we should have a call about this to see future steps.
Ping also @davidmegginson and @takavarasha to be in the loop

**Comment by danmihaila** [comment]
moving this issue to sprint 47 for further discussions

**Comment by cjhendrix** [comment]
Perhaps related to #1454 also.

**Comment by danmihaila** [comment]
as nobody is complaining I am closing this one. Feel free to reopen if we face any issues with search

**Comment by jbothma** [comment]
Sorry to necrobump - I just found this when looking into why searching for the example _Environment_ doesn't return an existing name "Environmental Affairs".

Has this since been solved or raised otherwise?

**Comment by longhotsummer** [comment]
@jbothma in our case, it's because "environmental affairs" is the name of a resource, which is stored as the field type "textgen", which is [not stemmed in the default CKAN schema](https://github.com/ckan/ckan/blob/master/ckan/config/solr/schema.xml#L117).
