### ISSUE TITLE
Research "Widget" Approach

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1996]
The main thrust of this issues is to figure out how we allow users to embed visualizations or other javascriptish elements on HDX pages **and/or** external sites.  A specific example to use:

A user wants to create a line graph similar to the Ebola cases graph on /ebola (excluding the onHover behavior) and embed it on her website. This implies

An interface (presumably on HDX) where she can: 
* point to a resource (assume datastore)
* filter the data in that resource (I think this is easily overlooked but critical)
* specify x and y axes units
* setting axis label properties
* setting color and line type properties for the line
* providing some copy/paste code or iframe URL that a user could embed elsewhere

In our brainstorming session, we discussed several approaches to this:
* iframing
* js module
* some third party software: tableau, pentaho, charted

Here is an interface that configures embeddable google maps just to get your gears spinning: http://mapbuildr.com/

Go be brilliant!

**Comment by aalecs** [comment]
Since the embeddable widgets are of different types (map/chart/etc) and might refer to different datasets, I researched a bit on how a widget like this is normally built.

The first step in a widget's life is the bootstrapping. This means the widget's code is being loaded inside the web page. Usually this is being done in two ways:
* simple "script" tag to load the bootstrap 
   * more straightforward 
   * remember to use the "//:" trick to handle http and https served pages
   * allows changing the bootstrapping script 
* embed an inline js bootstraping script
   * changing the script means the users need to reinclude the new script for the widget
   * script might be altered by mistake when user embeds it
   * remember not to put any important logic in it 
 
The next step in the process is to include the content of the widget inside the target page. This is usually done in two ways:
* using iframes
* by building the elements in JS and inserting them in the DOM

The second option is mostly used when the widget needs to be able to access the DOM or communicate with other elements inside the page, task that is a lot more difficult when using iframes. Also in this case a greater care is needed since the widget can easily alter elements inside the host page, override libraries with an older version or override css styling. So a greater care needs to be taken in this case to isolate the widget from the page. On the other hand iframes are isolated from the page and communicate easier with external servers (different domain) without needing to enable CORS.

All in all, iframes seem to be the choice for building embeddable widgets for HDX.

If we want to make the existing widgets embeddable, we need to refactor them and decouple their code and data from the pages they reside in right now. Also, great care needs to be taken with the included libraries in the bootstrapping process and fanstatic. We need to make sure that no static reference to fanstatic items reside in the widget user's page.
