### ISSUE TITLE
Create User:  improve feedback when email already exists

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2013]
When a user tries to create an account with an email that has already been used, the feedback is not clear that this is the problem. 

![image](https://cloud.githubusercontent.com/assets/1654485/5526663/5867811c-89f6-11e4-998e-53d89d01b475.png)

Let's change the feedback to read:

"The form contains invalid entries:
* Email: the email address is in use by another user"

If it is not possible to distinguish the error from other types of email related error (keep in mind that the API currently accepts erroneous emails even if the interface does not), then we could use this error message:

"The form contains invalid entries:
* Email: the email address is invalid or in use by another user"

**Comment by mbellotti** [comment]
Actually I'm looking at the code right now and it's throwing that error because the email address is not valid. If the email address was in use it would throw a different error ("That login email is not available"). Unsure what change to make here since bloggs@bloggs.com ISN'T a valid email to begin with so the code is doing what it was designed to do.

**Comment by cjhendrix** [comment]
I get it.  I'd used that same email address before we started validating the domains and I assumed the error was because of the duplication.  I'll close it.
