### ISSUE TITLE
Search Result Snippet: gallery, quality, subnational icons

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2101]
![image](https://cloud.githubusercontent.com/assets/1654485/5758187/3f966880-9cc3-11e4-91f5-0e7aef5f89c9.png) 

This issue is closely related to #2115

Three new icons to be added to the search result snippet.  Preferred ordering of icons (if they all were present) would be:

1. Indicator icon
1. Quality assured icon (new)
1. Gallery icon (new)
1. Subnational icon (new)
1. Popular icon

-----------------

- [ ] Add the [gallery icon](https://drive.google.com/file/d/0Bx1KWNTx8Ij3MkJORXRCaDZSck0/view?usp=sharing) to any ckan dataset search result that has >0 gallery items.  OnHover text = "Gallery Item"

If helpful, remember that we had code that checked for gallery items in order to put "XX New!" beside the gallery item tab in the old interface.  

- [ ] Add the [quality assured icon](https://drive.google.com/file/d/0Bx1KWNTx8Ij3Wk9jcFJWM2xOUWM/view?usp=sharing) to any dataset flagged as an indicator.  OnHover text = "Quality Checked"

- [ ] Add the [subnational icon](https://drive.google.com/file/d/0Bx1KWNTx8Ij3MzFPa1RpNElhMlU/view?usp=sharing) (from a flag on the dataset to be added in #2115) OnHover text = "Sub-national Data"

**Comment by cjhendrix** [comment]
@JavierTeran Please confirm if you want "Quality Checked by HDX" or "Quality Checked" as the onHover for the quality assured icon.  The former is assumed for now.

**Comment by cjhendrix** [comment]
Javier replied to the above.  I edited the description: onhover = Quality Checked

**Comment by alexandru-m-g** [comment]
@aalecs can you please add the SVG icons linked in the description of this ticket to the hdx-icons font ( via icomoon) ? Please use the branch **country-controller3**

The class names I used are: icon-quality_checked, icon-gallery, icon-subnational . They are used in package_item.html 
Right now I put some text in the respective "span" tags so that I can see them in the rendered page which can be removed afterwards.
