### ISSUE TITLE
Default Country Page: map

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2104]
Blocked by #2102 and #2103 
Annotated (very annotated) design is here: 
https://docs.google.com/drawings/d/1qOBKZ7IO7zkEMHh2g3ZiAynh5PiAbO-_-SL4rd9uO_M/edit
Implement the map section

**Comment by cjhendrix** [comment]
It was suggested that centroids might help with the map.  You can find the centroids in this dataset (which is private):  https://data.hdx.rwlabs.org/dataset/country-centroids

Feel free to use those centroids in the backend.  If we want to put them in the datastore, then I want to strip out some of the data and just use the centroids.  Let me know.

**Comment by aalecs** [comment]
@cjhendrix - I see that in the annotated design it's suggested to use the browse page map, which is different than the Colombia map. For now I used the same map as in Colombia for consistency, please tell me if I should switch.

Thanks for centroids, but right now we're using something else. I'm computing the bottom-left corner and top-right corner for the country polygon in order to be able to dynamically adjust the zoom level of the map. I realised this was needed in order to fit countries like Australia on the map.

**Comment by cjhendrix** [comment]
Good call.  Thanks for catching it.  I believe it should be the same map as Colombia (OSM-based).

**Comment by aalecs** [comment]
Apparently I commited the changes on the wrong issue no (#2014 instead of #2104), the commits are:
  - https://github.com/OCHA-DAP/hdx-ckan/commit/c5a7bea3518925ab6b439e66134b96fbb1e3b0f6
  - https://github.com/OCHA-DAP/hdx-ckan/commit/5693989429e11290e81acf51c11ee7cb8641988b
  - https://github.com/OCHA-DAP/hdx-ckan/commit/05c20dbf542393f24d552699814b097cfb1bc7c6
  - https://github.com/OCHA-DAP/hdx-ckan/commit/79ca294105c2ec10f23c41e1d503e6f25f3d6b19
Sorry! :)
