### ISSUE TITLE
Default Country Page: datasets&indicators list

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2108]
Blocked by #2102 and #2103 
Annotated (very annotated) design is here: 
https://docs.google.com/drawings/d/1qOBKZ7IO7zkEMHh2g3ZiAynh5PiAbO-_-SL4rd9uO_M/edit
Implement the section that is displaying the list of datasets and indicators

**Comment by alexandru-m-g** [comment]
@cjhendrix two questions:

1.  On the annotated design it says `So the “tabs” will be there and can behave as they do on /search (defaulting to the tab with the most results). ` . Not sure what you mean about "defaulting to the tab with the most results".
2.  "Show all indicators/datasets" links should point to the same page ( different tab ) and not to the /search page, right ?

**Comment by cjhendrix** [comment]
1. I think I imagined this.  /search doesn't do that and so this page doesn't need to either
1. Correct.

**Comment by cjhendrix** [comment]
As discussed:
- [ ] changes to "Advanced Search" to be styled like "show all indicators"
- [ ] remove the sections in the "All" tab so that it displays a mixed list of indicators and datasets, otherwise it is too busy, as shown in the screencap below:

![image](https://cloud.githubusercontent.com/assets/1654485/5942531/797b7702-a718-11e4-85d6-0d4c6a23b721.png)

**Comment by alexandru-m-g** [comment]
This commit actually belongs here: https://github.com/OCHA-DAP/hdx-ckan/commit/6790c97151de101943fbc20c08b5e4d43fdf090c

**Comment by alexandru-m-g** [comment]
This ticket is actually finished. Closing it.
