### ISSUE TITLE
Searching by country name string (q=somecountry) sometimes finds indicator datasets and sometimes not

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2155]
This search finds 92 indicators: https://test-data.hdx.rwlabs.org/search?q=somalia

While this one finds 0 indicators: https://test-data.hdx.rwlabs.org/search?q=mali

Trying different countries finds some with indicators and some without.

**Comment by teodorescuserban** [comment]
Searching for country iso code looks ok:
https://test-data.hdx.rwlabs.org/search?q=mli

**Comment by alexandru-m-g** [comment]
This is related to #283 :

*  since country names are not indexed in solr ( only their codes are ) a change was made so that: if a country name appears in the query, it's code would be transparently added to the search. Example:
  *  searching for "mali" would actually search for "mali mli"
  *  searching for "mali mli" would actually search for "mali mli mli" ( the country code is added at the end )
  *  searching for "somalia" would actually search for "somalia mli som" ( here we have an unwanted sideffect, because "mali" is a substring of "somalia" )
*  searching for "mali" ( which is actually  "mali mli" ) doesn't show any of the indicators tagged with country "mali". This is because  none of the indicators have the word "mali" in the document, only the words "mli", so:
  1.  **the solr documents representing indicators don't match both terms**
  1.  **because of 1 they get a lower score than the rest of the datasets**
  1.  it's the following solr query parameter that is causing documents that don't match at least 2 terms not to show up: "mm": "2<-1 5<80%". Still need to investigate this a bit, could also be that they just get a too low of a score ( "qf" param is influencing" )

Because of the unwanted behaviour I have reverted this change https://github.com/OCHA-DAP/hdx-ckan/commit/d71f79ae4135362c410ddecf553c572b30d4e813 .

**Alternative solution:**
What if we add a new extras field for countries ? ( Similarly to what we did for the indicator flag) All the "extras_*" fields are copied by solr into the "text" field which will then be search for any query.

**Comment by mbellotti** [comment]
.....This is why Google gets paid the big bucks ;)

It's unclear to me why this is a revert situation, versus a situation where we can tweak https://github.com/OCHA-DAP/hdx-ckan/commit/d71f79ae4135362c410ddecf553c572b30d4e813 to perform better for right now?

Although I like your country extras_ solution as well.

**Comment by alexandru-m-g** [comment]
@mbellotti I reverted it just because we need to do a release tomorrow morning ( so there was not much time to tweak this ) and #283 was actually meant for Sprint 47 but it got in Sprint 46 for some reason. Then the process is to merge all bugfixes from prod back into dev ( so that they have a common merge point ). 

We can still go this way if that's what we want and recommit the change and tweak it.

**Comment by mbellotti** [comment]
I'm just saying I don't really understand why a revert was necessary here, because even given the issues outlined above the search results with https://github.com/OCHA-DAP/hdx-ckan/commit/d71f79ae4135362c410ddecf553c572b30d4e813 are still closer to what we want than without, right? But it wasn't as if https://github.com/OCHA-DAP/hdx-ckan/commit/d71f79ae4135362c410ddecf553c572b30d4e813 created a critical error that made search or the site itself worse off. Or am I missing something?

**Comment by cjhendrix** [comment]
We reverted because the behavior was inconsistent from a user perspective.  "Mali" returned 0 indicators and "Somalia" returned too many.  We'll need to build a more robust fix for this in Sprint 47.   I've reopened #283.   Marianne, please organize the call you mentioned if you still think that's needed.

**Comment by cjhendrix** [comment]
Closing this one.  the long term fix is in #2155.
