### ISSUE TITLE
WFP page: template layout

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2200]
Implement the template layout with sections and sub-sections.
Design is here: 

https://docs.google.com/drawings/d/1PE5sAfD7Iii0Gfvp106ipqkamR37iLAwdgfXGfBROek/edit

Markdown needs to be parsed for the org description.

**Comment by cjhendrix** [comment]
Here is the WFP logo as PNG.  I have an SVG of it, so if you need a different format or more pixels, let me know.  https://drive.google.com/open?id=0Bx1KWNTx8Ij3ZFZURkg2X09JMms&authuser=0

**Comment by aalecs** [comment]
@cjhendrix in the redlines instead of the colours I have "WFP Blue". So I looked it up and it seems to be #0088FF according to this branding guide: http://home.wfp.org/stellent/groups/communications_content/documents/communications/wfp211867.pdf
But it looks a darker blue to me, should we use this colour for now?

**Comment by cjhendrix** [comment]
Yes, I think the document you found has the right color.  Or at least it looks more like what Frog has.  Let's use #0088FF

**Comment by aalecs** [comment]
@cjhendrix - please send me the SVG file, because the png has a different colour than #0088FF and the whole thing looks weird :)
