### ISSUE TITLE
WFP page: analytics

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2210]
We need to provide WFP with feedback on:
- [ ] The number of page loads on the WFP page
- [ ] The number of loads of each of the WFP dataset pages (regardless of where they come from)
- [ ] The number of loads of each of the WFP resources (filestore or datastore)

In the short term, this could perhaps come directly from google analytics?  Do some thinking, then let's talk.

In the long term, when we make the feature pages scalable, we may want to track these sort of metrics in ckan and expose them to org members through the interface.

**Comment by danmihaila** [comment]
I don't know how to test. @alexandru-m-g can we see a export from GA?

**Comment by alexandru-m-g** [comment]
What I did: 
- added a custom dimension in GA (called organization) which is then populated from the dataset pages with the organization title (via js).

Caveats:
- I tested that the information is sent to GA BUT i couldn't see it in the reports from GA. Could be because the code was locally and not on production website and/or because the report data has a delay of about 24h  ( and because custom dimensions are not shown in real time section)
- This only affects the data starting from the moment when the code goes to production ( doesn't affect existing data )
