### ISSUE TITLE
Custom Org Page:  controller

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2325]
related to #2299 
The Custom Org Page is based on the WFP page template and uses information from the org extras to populate the page with the org logo, highlight color (for the background graphic and dataset search result tabs), org description, topline numbers, and search results.   See #2298 for details.
- For the topline numbers:  assume the datastore has either 4 or 8 toplines (one row of 4 or two rows of 4).  It's ok if it breaks if this assumption is broken. 
- Search results is a standard filter by the org facet.

**Comment by alexandru-m-g** [comment]
@teodorescuserban 
I think the following will be needed in Dockerfile as RUN commands:

apt-get update
apt-get install nodejs
apt-get install npm

npm install -g less

   # lessc assumes node binary
ln -s /usr/bin/nodejs /usr/bin/node

**Comment by alexandru-m-g** [comment]
The following 2 configs need to be set in prod.ini ( NOT in common-config-ini.txt as these differ from env to env )

```
hdx.css.basepath = /srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/public/css/generated
hdx.less.basepath = /srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/less
```

**Comment by alexandru-m-g** [comment]
@teodorescuserban let's talk about a way of automatic compilation of custom less ( maybe at container startup ? )

I Added 2 ways of (re)generating all the custom CSS from LESS

1) on CKAN startup by setting in prod.ini: hdx.less_compile.onstartup = true -- in time this could become quite a long process
2) via a paster command: paster --plugin=ckanext-hdx_theme custom-less-compile -c /srv/prod.ini -- which would need to be run on any new container

**Comment by teodorescuserban** [comment]
After a call with @alexandru-m-g these are the changes of ckan image:
- integrating the second solution in the hdxckantool, something like `hdxckantool less compile`.
- adding the basepath lines to prod.ini template
- adding `hdx.less_compile.onstartup = False` in prod.ini template
- adding `hdxckantool less compile` on start script of the ckan service (we can comment it out once we see it takes too long because of the many orgs or something)

The outcome: less compile will run on every ckan service restart.

**Comment by teodorescuserban** [comment]
Done.
Please make sure you pull the latest ckan image.
