### ISSUE TITLE
Custom organization page should show private datasets

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2347]
For members of the org, the default org page shows private datasets.  This is the only place where members of an org can find these datasests (other than direct URL).   The custom org page will need to do the same.

**Comment by alexandru-m-g** [comment]
I made a change so that org members can see private datasets. When private datasets started appearing in the result list "Request data" appeared under the dataset name (check screenshot). 
I removed that and also moved the lock icon to the right ( next to the other icons ). 

![1](https://cloud.githubusercontent.com/assets/6586348/6567764/ccd73d8c-c6d5-11e4-862d-b26a279cffab.png)

@danmihaila @aalecs do you know anything about that "Request data" text appearing on the left ?

**Comment by danmihaila** [comment]
I don't know anything about this. Can you check in annotation if it is hdx or core ckan?

**Comment by alexandru-m-g** [comment]
I checked. It's our code. But each line from that template comes from a different commit ( almost). But I saw many lines from @aalecs  there, that's why I pinged him.

**Comment by aalecs** [comment]
@alexandru-m-g - Can't help you with the request data button - I might have made layout/styling changes to it, but I don't remember adding it :)

**Comment by alexandru-m-g** [comment]
Ok, thanks. Closing this issue.

**Comment by danmihaila** [comment]
@alexandru-m-g can you check if that code exists somewhere in core Ckan?

**Comment by alexandru-m-g** [comment]
I checked, couldn't find it.

**Comment by danmihaila** [comment]
my advice is to hide it, at least until @cjhendrix  will confirm.
Pinging also @amcguire62  and @ochadataproject for opinion about "Request link" from @alexandru-m-g 's screenshot

**Comment by alexandru-m-g** [comment]
As mentioned in my previous comment, that's what I did. The left part of the screenshot does not show.
