### ISSUE TITLE
White colored text on dataset page.

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2361]
When an user creates a dataset and doesn't add any resources a message that reads "This dataset has no data, why not add some?" appears. However, the part "why not add some?" is colored white, becoming nearly-impossible to ready. Here's the screen-shot:

![screen shot 2015-02-24 at 2 51 47 pm](https://cloud.githubusercontent.com/assets/953118/6357766/d8864ef8-bc34-11e4-8e83-4e60d5bc3660.png)

**Comment by cjhendrix** [comment]
Just a note on this: we haven't been maintaining that since the decision was made to prevent/discourage users from having datasets with no resources.    Since it would be hard to fully prevent users from doing that, and I think there are good use cases for doing so (while preparing a dataset, for example), so I think we should fix this.

**Comment by cjhendrix** [comment]
If we decide not to manually edit migrated COD datasets that have links instead of resources, this will definitely need to be fixed.
