### ISSUE TITLE
Custom org page: admin - allow users to upload logo1 and logo2

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2421]
For each custom org, in admin users will be allowed to upload two logos:
1. logo 1 - rectangular shape. The hint should specify size: https://docs.google.com/file/d/0B24NBcgmV490VXVXTl9pN0gzZmc/edit 300px X 125px 
2. logo 2 - square shape. The hint should specify size: https://docs.google.com/file/d/0B24NBcgmV490ek9OYVlyT2ZaWE0/edit  75px X 75px

**Comment by mbellotti** [comment]
Here's the status of this: the file upload works (for the most part), it just gets put in a place not web accessible so I think we need a solution similar to what we did with the filestore so that we can generate a url that can access and display the image.

I could use some help with this as I'm falling behind this Sprint :/
