### ISSUE TITLE
Org create/edit: LESS box resize doesn't work

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2436]
In Chrome, no resize is possible.  In FF, it can be resized slighly in the horizontal, but not vertical. 

![image](https://cloud.githubusercontent.com/assets/1654485/6665822/290c2646-cbde-11e4-8c06-dc04a41268f4.png)

**Comment by mbellotti** [comment]
Resize is not possible because the containing divs have a specific size and the containing divs have to have a specific size to hold the desired form design together. I suspect that allowing resize is not actually the issue we want to solve here. Can we close this one just by making the textarea bigger so that it looks a bit nicer and is easier to use?

**Comment by danmihaila** [comment]
I think a bigger hight and scrolling will be ok for the moment. @cjhendrix  ?

**Comment by cjhendrix** [comment]
Yes, a bit bigger is fine.  Scrolling would be nice, but not a big deal.
