### ISSUE TITLE
Custom Org Page: different URL for orgs using the custom template

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2443]
Orgs that use the custom template are redirected to /org/foo instead of /organization/foo.   Is this intentional?  @mbellotti

**Comment by mbellotti** [comment]
Yeah. We talked about this is Liverpool. Do you want me to merge the custom
org controller with the normal org controller?

**Comment by cjhendrix** [comment]
I leave it to you guys to figure out how to handle it, but I think users shouldn't see /org/foo.

**Comment by danmihaila** [comment]
I think we should use /organization/foo. I was not aware of any change until now...

**Comment by mbellotti** [comment]
Okay @alexandru-m-g and I have talked this over, basically the problem is that one route cannot direct to two completely different places. Here are our options:

1 - Merge Custom Org Controller and HDX Org Controller <--Cannot be done in time for deploy to production ... more to the point both Alex and I would prefer not to do it at all as it would make HDX Org Controller massive and difficult to navigate

2 - Call an Instance of Custom Org from inside HDX Org <-- The Hacky solution. Should in theory work, but really ugly and awful code architecture.

3 - Modify the route so that the url looks closer to the normal url <--- /organization/foo/custom should work, for example.
