### ISSUE TITLE
Custom Org Page: Improve topline numbers display

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2463]
We will need to improve the handling of topline numbers to ensure we can handle the range of values we are likely to see.  Currently, it's easy to end up with values that don't display well.  For example, using the Colombia Toplines in a custom org page results in this: 

![image](https://cloud.githubusercontent.com/assets/1654485/6691296/08438272-ccc6-11e4-9a35-de51c45125b5.png)

We need to consider how to handle:
- [ ] 2 line titles
- [ ] number/word combinations that are too long to fit in the box

**Comment by danmihaila** [comment]
@aalecs any advice/idea on this?

**Comment by aalecs** [comment]
- for the two lines title just set "height: 2em;" in ".topline .indicator-title" ... will force all indicators to have two lines of data so everything will look consistent.
- for the long unit names: set font-size: 34px; in ".topline .small"

Now the cool thing is that we can do all these overrides in the edit form for the custom org page, inside the "custom less" field :smile: 
So these overrides can be set just for this page only because the topline data is in that way.

**Comment by alexandru-m-g** [comment]
Trying to list below the worries from a previous discussion with @cjhendrix .

What about the case  when all the top line item names are short ?  If we leave space space for 2 rows and they are not used it might look weird.
A similar discussion is for the font sizes of the numbers and units. We can make them smaller but sooner or later someone will want them even smaller. 

Should we just have the org admin configure all this in the edit page ? Seems a bit complicated for the admin.

Maybe we need a discussion ?

**Comment by cjhendrix** [comment]
I think we need to avoid going too far with the idea of having users edit the LESS or CSS in the edit page.  Over the long term we want to make these edits something that a more typical user can do.   The LESS editing approach should just be a temporary approach for the early phases.

**Comment by danmihaila** [comment]
From @yumiendo :
bold highlight is the change:
indicator-value {
  font-family: 'Gotham-Light', sans-serif;
  font-weight: 400;
  **font-size: 56px;**
  letter-spacing: 0.01em;
  line-height: 1;
}
.topline .small{
  font-family: 'Gotham-Light', sans-serif;
  font-weight: 400;
  **font-size: 28px;**
  letter-spacing: 0.01em;
  line-height: 1;
  margin-bottom: 20px;
  margin-left: -15px;
}
is there a way in code to align the baseline of the big number?
Please see the screenshot.
![ngocons](https://cloud.githubusercontent.com/assets/3865844/6748475/a8cdfb6c-ceee-11e4-83c4-44710a81a1bf.jpg)
ping @alexandru-m-g

**Comment by cjhendrix** [comment]
Ok, for now let's just go smaller as yumi suggests and leave space for a second line in the titles.  But sooner or later I think we'll have to do something smarter.

**Comment by danmihaila** [comment]
From Sarah:
we had decided to change the wording 'global operations data' to 'key figures'

**Comment by danmihaila** [comment]
@cjhendrix I agree we will need to support different formats and lengths of numbers. Pinging @yumiendo

**Comment by alexandru-m-g** [comment]
@danmihaila @cjhendrix 
Please note that my commit doesn't change things for organizations that already have a custom page ( since the LESS & CSS is already generated for them ). Not even a regeneration of the CSS would help. Someone would need to change the LESS variables manually. 

I guess this is no problem for now but in the future, we might wanna save ( together with the organization) only does LESS variables that were explicitly changed by the user.
