### ISSUE TITLE
Datasets that don't preview well

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2508]
This is an issue for pasting in datasets that don't preview as expected so we can analyze the problem at some point when we have time:

Files reads as non-UTF8 (windows western according to Sublime), which might be the problem.  
https://data.hdx.rwlabs.org/dataset/evolution-of-malian-refugees-since-september-2012/resource/bdc01eb9-ed81-4887-bb64-f4317bf4221e   

The geojson file quite small and it has a preview button, but it fails to preview.
https://data.hdx.rwlabs.org/dataset/administrative-boundaries-cod-mli/resource/2011cd79-2a72-4a08-8c18-8210eb899005

**Comment by danmihaila** [comment]
@cjhendrix I can not reproduce this issue anymore
checking https://data.hdx.rwlabs.org/dataset/evolution-of-malian-refugees-since-september-2012/resource/88eb242f-f305-4ded-a51a-b0da18b6826d
and 
https://data.hdx.rwlabs.org/dataset/administrative-boundaries-cod-mli
looks that they are working well.
Closing this one
