### ISSUE TITLE
Custom Loc Page: Colombia map not working

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2580]
/group/col is set up to use the custom page.  The I've double checked the geo and values resouce ids and that they are valid files, but the map doesn't render.  The values dataset is in filestore, maybe this is the problem?

**Values:** https://test-data.hdx.rwlabs.org/dataset/json-repository/resource/e6cbd327-4846-4ea8-b8c0-c5c876af36bd
- parsed by sublime and https://json-csv.com as valid

**Boundaries:** https://test-data.hdx.rwlabs.org/dataset/json-repository/resource/0456462b-9111-4c5b-9621-3fa98d8d1661
- parsed by http://geojson.io as valid

**Comment by alexandru-m-g** [comment]
@cjhendrix The geojson file has some null "geometry" fields. ( Counting from the bottom, numbers 4,5,6 for example ). This messes up the javascript code that renders the map. I added a modified version to the same dataset as above and I can see the polygons on the map.

Some things are still not working but are probably due to the fact that the new configuration fields are not yet used on the "view" side

**Comment by cjhendrix** [comment]
Great!  Thanks for sorting that out.  I think the null geometries probably come from the simplification that was used.  It probably simplified some municipios to null.

**Comment by alexandru-m-g** [comment]
I did the following changes:
- use the threshold property
- use the values column property
- use the area name column property
- accept geojson with null geometry
