### ISSUE TITLE
API: provide a lighter version of group_show

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2639]
The H.Kiosk team would like to use our API to populate pages.   You can see the their [mockups](https://drive.google.com/file/d/0Bx1KWNTx8Ij3T0t6NXdMMTRhbGs/view?usp=sharing) to get an idea of what they are trying to achieve.  

Currently, our group_show response is quite large, making it impossible to use the API on the fly.  

If we are going to take this on, the H.Kiosk team would need it by beginning of May to integrate with their initial demo in mid-May. If we can't take it on in that timeframe, we just need to let them know.

**Comment by danmihaila** [comment]
https://test-data.hdx.rwlabs.org/api/action/hdx_light_group_show?id=mli

**Comment by alexandru-m-g** [comment]
@cjhendrix @danmihaila 
It's true that the package_search function call is rather complicated if there's a need for a way to get the list of all datasets for a group. In that case we could create a wrapper function call over the package_search function to make things easier.

**Comment by cjhendrix** [comment]
the h.kiosk developer will give us a list of what he would like to see.  We can take that as input, decide if there are some other things to add for more general use cases and build based on that.  

I can imagine it might be nice to get the basic info of the group (excluding the geojson!) along with a limited number of dataset returns sorted either by popular or last_modified.

**Comment by takavarasha** [comment]
My comment is on the topline figures and does not cover the dataset list aspect. I just wanted to point out that the user gave examples of Colombia and Algeria. Algeria does not have toplines. Instead it uses the ckan wrapper endpoint for the https://manage.hdx.rwlabs.org/public/api2/ to display the figures and graphs. I wonder if we should also present the option of the ckan wrapper api to the user. The justification being that so far, only Colombia (Mali to follow soon) uses the topline + datastores model to supply data for the country page, while the the rest of the country pages use data from the wrapper api. I think users should be allowed to access this data since the mechanism for doing so already exists.

**Comment by cjhendrix** [comment]
Great point, Godfrey.  From the user's point of view, we appear to have topline numbers for every location and an API user might expect to be able to call them.  The fact that some are coming from datastore datasets and some are coming from CPS should be transparent to them.

**Comment by danmihaila** [comment]
I think we need to decide what fields should appear in this lighter form.
Do you think it is a good idea to give the option to filter. For example user API could get org details + topline numbers, or org details+CPS details.
As main sections I suggest:
- [ ] Org information (what minimum information should be displayed here)
- [ ] Topline numbers (datastore or CPS - transparent for user)
- [ ] Charts datasets url ??
- [ ] Map dataset url ??
- [ ] Dataset list ?? or dataset query that could return list of datasets?

**Comment by alexandru-m-g** [comment]
I think there are actually 3 types of information that we're dealing with: basic group/country data, dataset lists for the group/country, and the top line numbers. The simplest way ( based on already existing functions) would be to have 3 different API endpoints so that a user of the API only fetches what he/she needs.
1.  Basic group/country data:
   - there's already an API method implemented for this on the staging server so it will be part of the next release: `/api/action/hdx_light_group_show?id=COUNDRY_CODE`
   -  this will give information like: title, description, geojson, related urls
2.  Dataset lists:
   -  the package_search API method that exists in core CKAN could be used for this. Example: `/api/3/action/package_search?fq=groups:dza +dataset_type:dataset&ext_indicator=1&start=1&rows=2` . It's quite powerful but not very user friendly.
   -  it allows for pagination, for filtering by datasets vs indicators ( and by all other solr stored fields ), for sorting
   -  We could make things easier here by doing one of 2 things:
     -  Create a helper & wrapper function over package_search with some nicer parameter names and nice defaults OR
     -  Add an option to hdx_light_group_show (1) to show the latest X ( 50 ? ) modified datasets ( Please note that that still doesn't solve the problem completely in case the API user is interested in seeing more than X datasets
3.  Top line numbers:
   -  we currently show information from 2 sources: datastore and CPS
   -  we could create an API endpoint that would make this transparent to the API user. Still, there's a caveat since the meaning of the fields can have slightly different meaning depending on the fields ( the units column for example is mostly used for formatting reasons in the datastore but in CPS it has more of a semantic value )
   -  I've created a google spreadsheet for mapping CPS fields to the datastore structure. This needs to be discussed before proceeding: https://docs.google.com/spreadsheets/d/1TdHWPorNSRfJWyph4chvH8QF_dHT5IDoSrv3D7L0_0I/edit#gid=0

pinging @cjhendrix @danmihaila

**Comment by alexandru-m-g** [comment]
@cjhendrix @danmihaila 
So in the next release there will be 3 api endpoints ( as mentioned above ). Please note that each of the methods has a documentation that you can see in the call response itself:
1.  Basic group/country data:
   - there's already an API method implemented for this on the staging server so it will be part of the next release: `/api/action/hdx_light_group_show?id=COUNDRY_CODE`
   -  this will give information like: title, description, geojson, related urls
2.  Dataset lists:
   -  `/api/action/hdx_datasets_for_group?id=COUNTRY_CODE&OTHER_PARAMETERS`
   -  Returns a paginated list of datasets for a group with 25 items per page. 
   -  other parameters that can be used are: 
     -  _page_: page number starting from 1
     -  _sort_: options for sorting are metadata_modified desc, title_case_insensitive desc, title_case_insensitive asc, views_recent desc, score desc ( only useful if query string is specified, should be combined with metadata_modified desc ). Defaults to 'metadata_modified desc'
     - _q_: query string
     - _type_: 'all', just 'indicators' or just  'datasets'. Defaults to 'all'
3.  Top line numbers:
   -  `/api/action/hdx_topline_num_for_group?id=COUNTRY_CODE`
   -  please note the field 'source_system' which can have values of either 'datastore' or 'cps'. Please read the caveats in the comment above

**Comment by cjhendrix** [comment]
Looks great Alex.  I've shared with our H.Kiosk colleagues and will let them know when it is on staging.

**Comment by reubano** [comment]
@danmihaila re: `Dataset list` above, what about `ckan.action.organization_show(include_datasets=True)`

**Comment by alexandru-m-g** [comment]
@reubano Yes, you're somewhat right. We could use the `group_show()` with the `include_datasets` flag set to **False** for to get the information mentioned in this ticket. That can be used instead of hdx_light_group_show() which was done when this flag was not available. 

Calling `group_show()` with the flag set to **True** is not advisable because AFAIK it doesn't have pagination and a country could have lots of datasets and will make the call slow.

**Comment by reubano** [comment]
@alexandru-m-g thanks, that's good to know. Btw, I've used [ijson](https://github.com/isagalaev/ijson) in the past to combat similar issues by streaming the json response:

``` python
from ijson import items
from urllib2 import urlopen

f = urlopen('http://example.com/large_response')

for record in items(f, 'path.to.records'):
    # do something with record
    pass
```
