### ISSUE TITLE
Custom location page: Threshold values

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2663]
When setting more than 5 intervals, the legend is missing one color. Check screenshot
I think we should support up to 7 intervals...
![screen shot 2015-04-14 at 14 50 06](https://cloud.githubusercontent.com/assets/3865844/7136086/af8948f0-e2b5-11e4-9b84-bfbfa630e41d.png)

**Comment by danmihaila** [comment]
@aalecs there is another issue related to threshold and legend. Godfrey comment "I reduced the number of categories on the map, but it the colors on the scale and those on map are not matching up (see pic). "
![mali](https://cloud.githubusercontent.com/assets/3865844/7198352/2d75fafc-e4f4-11e4-8daa-8653e9d7b325.jpg)

**Comment by aalecs** [comment]
New legend - max 8 colors:
![new_legend](https://cloud.githubusercontent.com/assets/5638491/7235440/d1c9bb6c-e796-11e4-9914-7f62400afb3d.png)
Each threshold based on the number of values in it, will have a different colour scheme attached so that threshold's with few values (1-4) won't have just light colours.

**Comment by danmihaila** [comment]
@aalecs did you try the example from Godfrey's comment?

**Comment by aalecs** [comment]
Yes ... fixed it ... if you check my comment you'll see that I've done more than that.
