### ISSUE TITLE
Search page: search bar doesn't search country (ckan group)

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#283]
Searching a country name via the text fields doesn't return a dataset assigned to the country (ckan group) unless the country name appears as a tag, title, or description.

Here is an example on staging (though it may be overwritten at any time; I don't want a public test of this on prod, so it isn't created there): 
https://test-data.hdx.rwlabs.org/dataset/a-test-for-country-name-searches

**Comment by cjhendrix** [comment]
From Marianne's email:  *May need to schedule a meeting regarding the fix itself as it is not the most efficient solution available, but the most efficient solution would require changes to core file ckan/lib/search/index.py that ckan core is unlikely to accept back. For now we are intercepting search request and checking for countries, then adding the appropriate country codes (group names) to the queries before sending them to solr so that datasets assigned to that country without the country name in the title/description still show up. It will work well for now, but we'll want to keep an eye on it.*

**Comment by alexandru-m-g** [comment]
Added a comment related to this issue in #2155

**Comment by mbellotti** [comment]
May have spoke too soon on this one. I tested the new strategy tonight and datasets without country name in title or description do not come up. However, run the same query directly through solr and they DO come up ... not sure why that is. Thoughts? @alexandru-m-g

**Comment by alexandru-m-g** [comment]
@mbellotti I think it'll be easier if I take the code and test. Can I take the latest code from marianne-dev ?

**Comment by mbellotti** [comment]
Yes sir!

On Fri, Jan 23, 2015 at 5:55 AM, Alexandru Gartner <notifications@github.com

**Comment by alexandru-m-g** [comment]
@mbellotti I've tested a bit on my computer and:
*  if I understand correctly, adding country names to "solr_additions" is done via javascript on the form page -> this means that if I just edit and save an indicator the countries won't be indexed by solr
*  On the other hand, if i edit an indicator and remove a country and then add it back ( the js code will come into action ) and country name is indexed. I tried this with "Algeria" and "Routine EPI vaccines financed by government" and I could then find the indicator by searching for "Algeria"
*  There's an issue with datasets created/updated from the API since then we would need to explicitly send the country names in a "solr_additions" field ( The groups field will not be enough )
*  IMHO, it will be safer to do the populating of the "solr_additions" field on the server side based on the "groups" list, at saving time. That way we would insure that the "solr_additions" list is consistent with the "groups" list. This would probably mean that we could only store countries in that field otherwise it would be difficult to refresh it. But it's probably not such a big disadvantage
* in any case, **none of the indicators/datasets will have the countries indexed in solr until the time that they are saved again. I think this is not such a big issue though, as for indicators, we can push again the countries from CPS** ( This wouldn't be a solution for the other datasets though ). @cjhendrix, would that be acceptable ?

**Comment by mbellotti** [comment]
@alexandru-m-g No, that wasn't what I was talking about. I was aware of this issue and was planning on writing a script to update all the current datasets

What I'm seeing as I test is this:
- create a new dataset, assign some countries
- search for one of those countries in CKAN, new dataset does not appear in search results
- search for country directly in Solr, new dataset does appear

There's no point to updating current datasets until we can confirm that this solution works. Are you seeing different behavior?

**Comment by alexandru-m-g** [comment]
Works for me, check screenshot below. Although sometimes, if there are many results, it won't appear in the "All" tab.

Just to reiterate the point above, I think we need to make sure that this new field is always synced with the groups field. Even for data that comes over the API. 

![snapshot1](https://cloud.githubusercontent.com/assets/6586348/5879142/432930ae-a335-11e4-9ae2-21f1734103af.png)

**Comment by mbellotti** [comment]
Well I suppose that's good then *lol*
