### ISSUE TITLE
Search: predictive

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2832]
Research how we could achieve what Yumi described in the screenshot attached.
Basically the search should suggest:
- custom crisis pages
- organization pages (custom and non-custom)
- location pages (custom and non-custom)
- datasets
- indicators
  How difficult is to achieve it and what is the estimate.
  ![predictive-search](https://cloud.githubusercontent.com/assets/3865844/7587376/74998d58-f8be-11e4-90f8-0a9ef334e8d2.png)

**Comment by reubano** [comment]
take a look at [Typeahead.js](https://github.com/twitter/typeahead.js)

**Comment by mbellotti** [comment]
So... can it be done, sure! But doing it the most efficient way is what poses the challenge. There are some trade-offs that we need to establish priorities around.

To begin with, CKAN's default autocomplete function does not actually do a proper search, instead it runs a LIKE query with a double wildcard over a specific column (generally name) on a specific entity (user, tag, etc). There are some potential performance issues around doing things this way (great technical explanation here --> http://use-the-index-luke.com/sql/where-clause/searching-for-ranges/like-performance-tuning) but it's not a huge deal.

However, in this case we want to match partial strings over multiple entities and potentially multiple columns (or elements in the case of solr). Since the organization and country names are stored in the solr index already, pulling up matches to full words is not a problem. When we have actual crisis pages, adding another element to the solr index should allow matches here too.

But there are two big challenges here:
1. Figuring out where the match the autocomplete should suggest actually is within the results Solr returns. It could be the name of the dataset matches, it could be the name of the group the dataset is in matches, it could be the name of the organization the dataset is in matches. We would need to develop a good way to iterate through the results Solr returns and identify what the suggestion should be. It might actually be more economical to build a completely separate solr core (basically just an index) that only stores display names of datasets, groups, and the organizations for this purpose. It will be a bit tricky to do this without modifying the ckan core files, but it's possible if we assume that we are not interested in orgs, groups, or crisis that have no datasets assigned to them.
2. Getting Solr to match string fragments in the first place. CKAN's default solr configuration does not use ngram filters, so querying "nepal" will return everything that matches nepal, but querying "nepa" will return nothing. Autocomplete requires those substring matches and by enabling ngram filters solr will be able to produce matches along those lines. The thing is ngrams can be kind of expensive depending how aggressively you use them, because essentially you're indexing not just the full string, but multiple fragments of it. If we were to enable this on our current solr core we would have to enable it in at least three different places (dataset name, organization name, group name). People have done this before (http://www.andornot.com/blog/post/Advanced-autocomplete-with-Solr-Ngrams-and-Twitters-typeaheadjs.aspx), but I think this approach is probably a bit greedy with resources. If we build a new core we only have to enable it in one place, but we still have to decide how sensitive we want the search to be.

Given those considerations, this is what I would suggest:
- Build a new solr core that stores only the display names of the entities we want autocomplete to be able to suggest and perhaps a boost score based on how we want to prioritize them (I'm a bit more familiar with how this works in Elasticsearch, but I'm sure Solr can do it)
- Hook into the after_update and after_create elements of IPackageController so that every time a package is updated or created its name, and the groups and organizations it belongs to are added to the new core.
- Write a new autocomplete function that queries this index and returns a list of suggestions

**Points for Clarification:**
- What is the expected behavior of this interface? When the user selects an option from the list, do they get automatically redirected to that dataset, group, or organization? Or do we just proceed with the search as if they had typed the whole word themselves?
- What is our ultimate scaling strategy? (@teodorescuserban) Do we have the freedom to spin up new servers and build clusters as our data grows? Or do we need to be extra mindful in how we use our available resources because adding additional servers will be a difficult task?
- What is the smallest fragment that we want to match on? In other words, which of these should trigger a search that returns "Nepal" >> "n", "ne", "nep", "nepa"....?

**Projected Time:**
I think I can do this in one Sprint, maybe one and a half. It will be one of those tricky to deploy features though, as we'll have to configure Solr with a new core on each server.

**Comment by mbellotti** [comment]
tagging in @alexandru-m-g for his thoughts :)

**Comment by reubano** [comment]
You can also offload some of the processing client side https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md

**Comment by cjhendrix** [comment]
Our existing autocomplete functions perform very slowly (in particular the format selector on resource create/edit.  In the past we have said we would minimize use of autocomplete because of concerns with performance in field locations. Should we make sure that this will perform well in the field (perhaps by trying to fix the file format selector) before making it central to our interface?

**Comment by danmihaila** [comment]
I will set a call for tomorrow about this to discuss pros and cons and to decide what is the best solution we could think about it.
Until tomorrow, @mbellotti can you check @reubano 's solution regarding search on the client side?

**Comment by mbellotti** [comment]
We can't offload any of these issues to the client side. Reuben's solution is basically a cache. You can give it a predefined list of suggestions to store locally, if autocomplete can't find a good match it goes back to the server and runs a search .... at which point we have to address all the issues above.

Bloodhound is really more about minimizing the amount of queries sent to the server to retrieve essentially the same information (which is good, don't get me wrong), switching to Typehead+Bloodhound may very well improve the speed and smoothness of the autocomplete interface but it does not solve the core problem of how to best query multiple fields. More to the point, Bloodhound will not prioritize certain matches over others and I got the impression that we'd like this feature.

Typeahead.js is only worth talking about if we're willing to rip out ckan's default autocomplete library and replace it with something else, which I didn't think was on the table.

**Comment by teodorescuserban** [comment]
We can scale.
That's one of the perks of docker.
Let's what are the initial requirements and choose whats best.

Mie, 20 mai 2015, 14:09, mbellotti notifications@github.com a scris:

**Comment by reubano** [comment]
An alternative to typeahead is live search. I've used [lunr.js](https://github.com/olivernn/lunr.js) in the past and it allows you to weigh matches by field, .e.g,:

``` javascript
var idx = lunr(function () {
    this.field('dataset_name', { boost: 10 })
    this.field('organization_name', { boost: 5 })
    this.field('group_name', { boost: 2 })
})
```

See it live [here](http://africastalking.herokuapp.com/). Doesn't completely solve all the issues mentioned above, but I figured it'd be good to know the options.

**Comment by alexandru-m-g** [comment]
Here are my 2 cents:
-  We have about 400 organizations, groups and crises in total. As I understand, we only need to search through their name and description fields so **pushing this to the client ( browser )** shouldn't pose a problem. Just as a rough estimation, a CSV with >6000 lines with 3-4 fields takes about 900KB, and gzipped ( the way it reaches the browser )  it reaches about 35KB. So even if the number of orgs, groups and crises rises 10x, we can still push this information to the browser and let the client do the search. Not to mention that this could be easily cached both client side and server side.
-  Searching through datasets is a bit different since we'll soon be reaching 2000 and I guess this number could explode.
  -  Again if the predictive search should just check the name and description field we could have a server side (in memory) cache that is used and just search in it without hitting either solr or the database
  -  If the number of datasets grows alot, we could configure our solr core to match on string fragments and, if needed, to have a distributed solr environment. But I would suggest to only go this way when needed.
-  Given the points above I would avoid for now to create another solr core

**Comment by mbellotti** [comment]
Okay, this is good point, we _could_ push this information to a file accessible to a client side solution, but we'd still need to program the hooks to control adding and updating that cache when the underlying entities update. This issue: https://github.com/OCHA-DAP/hdx-ckan/issues/2378 is the result of a similar caching a list strategy and the powers that be are not happy with its performance.

Also it goes back to the question of what should happen when the user selects an option from the autocomplete list. If the idea is to just run a search, then Alex's solution could work. If the idea is to redirect the user immediately to the entity that matched then it might be more complicated?

I disagree about enabling ngrams on our current solr core for the simple reason that it will produce a whole lot of unnecessary duplicate information from groups and organizations. I think a separate core would be a whole lot more efficient should it come to that.

**Comment by alexandru-m-g** [comment]
@danmihaila since there are some questions about the exact requirements for this ticket do you think it would be helpful to have @yumiendo in the call ( at least in the beginning ) ?

**Comment by mbellotti** [comment]
Closing for now.

**Comment by reubano** [comment]
So what is the conclusion?

**Comment by danmihaila** [comment]
We will do this after upgrading 2.3 I will reopen this issue and add it to backlog for the moment

**Comment by amcguire62** [comment]
Given we will soon deploy 2.3 want plan in a call to review options in the context of what we want to achieve and what is MVP to improve user experience. Specifically want Sarah and Yumi on the call to set priorities then once we are clear on priorities we then distil down to what options are best  given what we want to achieve .

**Comment by danmihaila** [comment]
duplicated by #3139 , closing this one
