### ISSUE TITLE
Research: 2.3 visualizations

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2845]
Research how visualizations (views) in 2.3 are done.
1. How to attach a view to a resource
2. how to develop a HDX view template ? e.g topline numbers, chart (single line)
3. each view generate an iframe. How can we integrate views in other pages (custom orgs, crises, etc)
4. how to build a crises? can we use visualizations

**Comment by aalecs** [comment]
After doing a bit of research on the resource view's in CKAN 2.3 I can say the following: 
- they are a nice addition and surprise :)
- we can create extensions with different types of views which can have their own fanstatic resource bundles (so we can have different versions of libs)
- they can be rendered in an iframe to avoid lib version clashes and this means for us we don't have to write controllers that generate the widget out of it's context so it can be embedded in another site
- the configuration part of the view is nicely handled by having a template with all of the fields necessary - these will render automatically in the edit page of the dataset when a resource view is added to the dataset (hope we can integrate this behaviour in our group/org pages :smile: )

I think at first we could migrate our embeddable widgets to become extensions that provide resource views and see how well they work out. And for our crisis pages we'll have to check out how the resource views can be integrated in groups and organisation pages so that they will be configurable.

I discussed with Dan also the case of a resource view that needs additional resources in order to render (eg. shapes for districts). I think these resources will be added as configuration fields in the main resource view.
