### ISSUE TITLE
Relevance sorting on search seems odd when searching for CODs

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2970]
The following search "afghanistan common operational dataset" (on stag) does return the desired dataset, but only as the 6th entry (Afghanistan Population Stats).  That dataset contains a tag "common operational dataset".  

![image](https://cloud.githubusercontent.com/assets/1654485/8325790/64596aca-1a5c-11e5-8459-2e19372bcc61.png)

Is it because the title is weighted higher?  Maybe we could tweak this a bit to make it easier to find the CODs.

**Comment by alexandru-m-g** [comment]
@cjhendrix Yes, titles are more important - check here: https://github.com/OCHA-DAP/hdx-ckan/blob/dev/ckan/lib/search/query.py#L26

QUERY_FIELDS = "name^4 title^4 tags^2 groups^2 text"

**Comment by cjhendrix** [comment]
I assume the last item, "text" is the description. If that's so, I would propose 
"name^2 title^4 tags^4 groups^4 text"

But where is are the orgs?  I'm pretty sure we are searching that too.

**Comment by alexandru-m-g** [comment]
Basically every field that you don't see above is concatenated together in "text".

**Comment by cjhendrix** [comment]
So then I'd suggest adding organizations^2 to the list above.   That's just my gut feeling based on the search terms analysis we did and the problem we will face with people searching for the CODs

**Comment by alexandru-m-g** [comment]
Just orgs ? What about description ?

**Comment by cjhendrix** [comment]
That would be part of "text" no?

**Comment by danmihaila** [comment]
I think this requirements should be part of the new search module. I am just guessing that in case we will make another SOLR schema or maybe to improve the current one...
ping @mbellotti to be aware of this discussion

**Comment by alexandru-m-g** [comment]
1) This is not part of the solr schema
2) Are we modifying the schema for the new search module ?

**Comment by alexandru-m-g** [comment]
@cjhendrix Why would Afghanistan Population Statistics be higher ? I don't see the words "common" or "operational" in the description of the dataset. 

I only see the COD tag

**Comment by cjhendrix** [comment]
I think Serban re-ran the cod migration (which would have deleted the "common operational dataset" tag that I added manually).  Trust me, it was there.    :)

**Comment by danmihaila** [comment]
@mbellotti and @cjhendrix please discuss and coordinate about this issue.

**Comment by cjhendrix** [comment]
I think the basic test we are trying to pass here is that when a user searches "[country name] cod" that the first results that come back are those where location = [country name] and tag = cod

**Comment by danmihaila** [comment]
@cjhendrix @mbellotti @amcguire62 to have a call this week

**Comment by mbellotti** [comment]
Proposed solution agreed upon in our call:

### Create a COD group
- Data team will create a group titled "Common Operational Datasets (COD)" and place all the existing COD datasets in it @takavarasha 
- I will take the id of that group (probably something like cod-migration) and update the lunr index so that it is listed as a **Feature** page rather than a Location page.

### Tweak Dataset Create/Edit
- Dev team will make sure COD group does not appear in country dropdowns on the HDX
- @cjhendrix will have to provide a list of approved OCHA organizations (see below)
- Dev team will add a checkbox to the dataset create/edit interface asking the user if this dataset is a COD. This checkbox will be visible to only members (admins? editors? @cjhendrix was unclear about what role he wanted to restrict by) of specific OCHA organizations
- Dev team will modify dataset_update action to check for the COD flag. If present, HDX will automatically add dataset to COD group and tag dataset with COD tag (for good measure)

### Test and Modify
- Lunr may need to be tweaked slightly depending on how well it handles partial matches ("[country name] COD" versus "COD [country name]")

pinging @amcguire62 ;)

**Comment by alexandru-m-g** [comment]
I was thinking there might be a solution that combines the 2 ideas that were discussed: **have a new dataset field** that for lack of imagination i'll call **very_important_dataset_field** 

### Advantages:
-  It's importance could be boosted as much as we wanted 
-  searches that are not related to COD won't be affected
-  we don't need to artificially use groups for something that's not actually a location
-  we could reuse the field in the future for other datasets that need to show up in the top of search results

### Steps:
1.  Add this new field in CKAN
2.  Make it available in dataset form:
   -  either as a simple text box that selected users can fill with whatever text they need OR
   -  as a checkbox that tells CKAN to copy the tag values to **very_important_dataset_field**
3.  Boost this field's relevancy as much as we want

**Comment by mbellotti** [comment]
So here's what I keep coming back to on this. Assuming I understand the
situation correctly and all the COD datasets will eventually be changed so
that none of them have Common Operational Dataset in the title but all of
them are tagged Common Operational Dataset ... why do we even need to do
anything to search at all?

The five datasets that are ranked above the one we want to be number one
are ranked that way because they have the words "Common Operational
Dataset" in the title. When that is removed, the correct dataset will
likely be scored at number one, giving everyone what they want.

Why are we discussing changing the code to fix a data problem when we can
just fix the underlying data problem?

On Wed, Aug 12, 2015 at 3:22 AM, Alexandru Gartner <notifications@github.com

**Comment by cjhendrix** [comment]
@mbellotti I don't think it will fix the problem.  As a further test, I got rid of all the datasets with COD in the name.  Searching now for "COD" still returns all of the DR Congo datasets **because "cod" occurs in the location url** before a tagged dataset.  So I think at the very least we have to tweak the solr weights to bump tags up above the "text" item.

**Comment by mbellotti** [comment]
Wait... will the final tag be "COD" or "Common Operational Dataset" or both?

I'm still not comfortable with messing around with search. There are lots
of things that we could do that will benefit the user experience across the
site in a variety of different use cases. We could make filters and how to
use them clearer. We could move forward with Feature Pages and start
producing collections of data that we know people are looking for.

Just throwing this out here: a COD group will also give something for
people to confidently bookmark and link back to, thus boosting HDX's SEO

**Comment by cjhendrix** [comment]
Yes, final tag is "cod" not "common operational dataset".  Tagging @amcguire62 since I notice he's not getting in on all this commentative goodness. 

I agree, lots we could do to make it better.  But we still need 
/search?q=_country name_+cod 
to return the cods for that country first, which I _think_ means tweaking the search params.

**Comment by danmihaila** [comment]
Talking about tweaks if search we could also think at nginx or even the search controller...

**Comment by alexandru-m-g** [comment]
Based on @teodorescuserban idea about filtering by "cod" here is another idea: What if ( in case the word "cod" appears in the search query ) we show a suggestion like **"do you wanna filter by label 'cod' ?"**.

**Comment by danmihaila** [comment]
the next steps:
1. @teodorescuserban  will deploy staging server with latest stag code with clean db from prod
2. @teodorescuserban  will run gospawn and be sure the COD datasets are imported on feature server and let CJ know
3. @cjhendrix  will perform several searches related to [country]+COD and come back to us.
If results are not good we will think to boost tags.
Assigned to @cjhendrix

**Comment by cjhendrix** [comment]
for number 3 above, the searches are actually looking pretty good.  
`[country name] + cod` and `cod + [country name]` are returning the public cods for the country. 

We fall down on things like `north korea cod` because we use the more formal country name, but we can't solve that until we add short names/alternative names to groups in ckan.

**Comment by alexandru-m-g** [comment]
I'm still wondering if a "very important" text field ( as explained in a comment above) that is available only to  a restricted group of users wouldn't be helpful for making the search results more friendly.
