### ISSUE TITLE
Consider how we handle datasets that are "orphaned" in postgis by resource deletion or updates

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2973]

**Comment by alexandru-m-g** [comment]
1.  Send signal from  resource_delete() action
2.  Delete corresponding PostGIS tabel
3.  Delete mapping from  Spatial Server ( might not be necessary if we consider that as long as the resource is deleted, the respective endpoint won't be hit anymore. At the next restart the url mapping is not created anymore since the PostGIS table doesn't exist anymore )

**Comment by cjhendrix** [comment]
downgrading to medium after our recent discussion

**Comment by alexandru-m-g** [comment]
This is basically duplicating https://github.com/OCHA-DAP/hdx-ckan/issues/3466.

Closing this ticket.
