### ISSUE TITLE
Sitemap extension: improvements

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2990]
It is needed to check the performance of our extension to provide information about all our pages to search engines. This will improve our visibility. Ping @yumiendo, @cjhendrix and @amcguire62 
- [ ] small research about site.xml structure and if HDX site.xml is valid. Check also what are the recommendations
- [ ] add organizations to site.xml
- [ ] add locations to site.xml
- [ ] add static pages to site.xml (about, config, etc)
- [ ] add crises pages to site.xml
- [ ] Checking if such links are ok to be displayed (xlsx resources without a valid preview): https://data.hdx.rwlabs.org/dataset/aia_baseline_data/resource/af5c1aab-a24a-4d10-91e6-bff933e00310
- [ ] Check how many items are displayed in file like: https://data.hdx.rwlabs.org/sitemap1.xml

**Comment by mbellotti** [comment]
Couple of thoughts here:
Sitemaps are really just a tool to give webcrawlers somewhere to start, to help them find content that is not necessarily well linked and to give Google some sense of the structure of a site. It's not necessary to list every single page on the sitemap, a crawler will index organization and location pages by following links to them on the datasets listed on the sitemap

If improving our SEO is a concern there are far better ways to do this. One of the best ways is to blog more often, linking back to key HDX pages from those posts. Continuous browsing is a great SEO resource for this reason.

Also a month or two ago Google announced that their new ranking algorithm was going to basically punish sites that do not perform well on mobile. Which means that HDX pages will be ranked lower even when people are searching on their desktops because CKAN's default templates are not especially responsive.
