### ISSUE TITLE
Dataset Format : displays "csv" and "CSV" as different formats

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3068]
Dataset List: in the filter list on dev, “CSV” and “csv” are different formats.  On prod, these are combined (which is the desired behavior)
We should check if there are other cases like this. I think there are 2 options
1. We should try to merge them like we did for tags via script and be sure user can not add upper case formats
or
2. display only "csv", but when filtering it should show datasets with "CSV" and "csv" formats.
<img width="625" alt="screen shot 2015-07-13 at 13 30 04" src="https://cloud.githubusercontent.com/assets/3865844/8647741/58f682d8-2963-11e5-8fa2-f257b3555990.png">

**Comment by alexandru-m-g** [comment]
This should be more closely investigated. I noticed that when i save things with "geojson", when you retrieve the data via API it's actually "GeoJSON".

**Comment by alexandru-m-g** [comment]
Ckan core changed the way it deals with the format field. Now there is a json configuration file called: `resource_formats.json`. This file allows (among other things) one to map different alternative names to a single "official"  format.

I've created a copy of this file in our own extensions and changed the common config to read from this new file which we can modify at will. That's how I got .csv and .xlsx to map as CSV and XLS. 

This solves the problem when creating or updating resources but it doesn't deal with existing resources. In other words, when you do a solr reindex, existing datasets will still have formats as "GEOJSON" (in sorl) if that was the original format name and that makes the search facets looks ugly. To deal with that I've intercepted the before_index() function in plugin.py (hdx_search extension) and ran the `unified_resource_format()` on the formats before they are sent to solr. More precisely i've ran a modified version of the ckan core function (read below).

This, unfortunately doesn't deal with format names that are not part of that json configuration file. The same format written in lower case and upper case would still be treated differently if not part of the configuration. To solve this, I've slightly modified the `unified_resource_format()` function from ckan.lib.helpers so that it transforms to lowercase all these formats. This happens before the data is pushed to solr.

**Comment by alexandru-m-g** [comment]
@danmihaila @teodorescuserban 
A reindexing will be necessary for the changes to take effect.

**Comment by cjhendrix** [comment]
Great solution.   @alexandru-m-g While you have your head into this, I wonder if we could force them all to lower case?

**Comment by teodorescuserban** [comment]
Is this implemented to prod yet?
If so, I should reindex solr.
@alexandru-m-g ?

**Comment by alexandru-m-g** [comment]
@teodorescuserban I think this is already on production. So a reindexing is needed (if it wasn't already done at upgrade time)

**Comment by teodorescuserban** [comment]
Thanks I will.

În Joi, 20 aug. 2015 la 13:58, Alexandru Gartner notifications@github.com
a scris:
