### ISSUE TITLE
Dataset Create: change behavior of name field with uploaded file to avoid breaking previews

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3105]
Dev team may already  be looking at this, but we need to consider how the name field behaves in 2.3.  Before, once the file was uploaded, the file name would be used for the resource name.  Now, this isn't happening (because the actual upload doesn't happen until the form is submitted).

For consistency most existing resources, I'd suggest we capture the file name and populate the resource name field when the file is selected.  Tagging @amcguire62 @yumiendo for opinions/approval.

**Comment by yumiendo** [comment]
@cjhendrix Im happy with the solution suggested !

**Comment by cjhendrix** [comment]
Until this is fixed we may want to make the resource format a required field, since it is not being generated automatically from the file name.

**Comment by alexandru-m-g** [comment]
@cjhendrix the process will be:
1.  After the user chooses a file, the file name is being copied in the _name_ field
2.  The format can be empty and the server will try to guess the format based on the file extension. If it cannot figure out a format ( because the filename has no extension or because the url is something like http:// yahoo.com ) then the user will be asked to provide one. Check screenshot
   ![1](https://cloud.githubusercontent.com/assets/6586348/8839420/e4a08fc8-30dd-11e5-9285-27bce3bfac3e.png)

**Caveat:** The name of the resource might not be exactly the same as the file that the user would download. Currently CKAN removes characters like '-', '_' and others from the filename stored in db.

**Comment by cjhendrix** [comment]
I like the approach.  Pinging @yumiendo in case there are design changes to make. 

CKAN renaming the files is a bit problematic.  OCHA has been pushing a standard file naming convention (primarily for the COD/FODs) for years and this will break that.  I think we can live with it for now.  But how deep into ckan core would we have to dig to change that.  And why did they do that?  Seems unecessary.   Just to make the URLs nicer?
