### ISSUE TITLE
Misalignment on pages with black left panel

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3284]
Example:
![image](https://cloud.githubusercontent.com/assets/1654485/8953039/42619d2a-35dc-11e5-8b66-1fcbd47c00d4.png)

Seen on these pages:
https://data.hdx.rwlabs.org/organization/innago (at least I don't think v0.9x was like this)
![image](https://cloud.githubusercontent.com/assets/1654485/8953104/83669ece-35dc-11e5-8e48-2f76eb649a5a.png)

https://data.hdx.rwlabs.org/user/edit/cj

https://data.hdx.rwlabs.org/organization

https://data.hdx.rwlabs.org/user/reset

**Comment by danmihaila** [comment]
This change has an impact on other pages as well. Please double check this change, because it changes many things.
One sample is loc page:
![screen shot 2015-08-10 at 16 16 36](https://cloud.githubusercontent.com/assets/3865844/9172298/57ba19ce-3f7b-11e5-9c67-763e27b02dbd.png)
Also, default org page the grey horizontal line is stopping (not reaching black left side):
![screen shot 2015-08-10 at 16 18 39](https://cloud.githubusercontent.com/assets/3865844/9172323/8e072c24-3f7b-11e5-8e19-611cfd030b27.png)

**Comment by danmihaila** [comment]
the issues I posted in my comments are solved, but the initial issue is back again. Reopening...
![screen shot 2015-08-13 at 10 11 59](https://cloud.githubusercontent.com/assets/3865844/9244435/d3b5dd90-41a3-11e5-8b2a-b277be45299a.png)
![screen shot 2015-08-13 at 10 11 56](https://cloud.githubusercontent.com/assets/3865844/9244436/d3b8f854-41a3-11e5-8e3c-1ea375542786.png)

**Comment by danmihaila** [comment]
moving this one to sprint 63

**Comment by aalecs** [comment]
Reopening this for sprint 64 here is the screenshot of the problem:
![83669ece-35dc-11e5-8e48-2f76eb649a5a](https://cloud.githubusercontent.com/assets/5638491/9495538/b1031d46-4c14-11e5-9c09-2d0aa686f873.png)

**Comment by cjhendrix** [comment]
I just now added a url to the bottom of the issue description above.  It's another page where I see this issue.
