### ISSUE TITLE
Organization List: Add a sorting option "number of public datasets" and make it the default

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3534]
Currently we sort alphabetically, but it might be more useful (both to users and as an incentive to orgs) to sort by the number of public datasets (descending).  

![image](https://cloud.githubusercontent.com/assets/1654485/9844417/6f342884-5ac3-11e5-8824-95afc9b96132.png)

**Comment by cjhendrix** [comment]
@ochadataproject suggested "popular" as a sorting option also.  We would need to add tracking of some metric of org popularity (org page views, total datasets, total views of an org's datasets?)

**Comment by mbellotti** [comment]
I don't have anything in the org dicts right now that I can use as popularity, but if you settle on the criteria I can probably add it?

**Comment by cjhendrix** [comment]
@ochadataproject @yumiendo We didn't quite settle on how to define "popularity" for sorting organizations.  I suggest we use the sum of all recent views on datasets belonging to the org (ckan already tracks that).    Does that sound reasonable (and technically feasible) to everyone?

**Comment by mbellotti** [comment]
Not sure how efficient that is from a technical point of view. Let me play with it tonight and get back to you.

**Comment by mbellotti** [comment]
Okay, so here's the deal: the function organization_list which is what produces this list does not include the option to list all the datasets in the organization (which is just as well as the resulting dictionary would be HUGE) The number of views/downloads is stored in the package dict, not the org dict. So we can do this by modifying the org_dict but it's not a simple thing and will take way more time than I estimated for this issue. My Recommendation, if you really want this feature, letting this issue close and opening a new one.

**Comment by danmihaila** [comment]
@mbellotti pls check this commit, I think @alexandru-m-g did something similar for @aalecs removing the deleted datasets.
Edit: this is the url: https://github.com/OCHA-DAP/hdx-ckan/commit/30eb2bc2313a52fc2d839fffb191c6c5f61786d9 I am not sure if it helps, but we could do something similar.
If there is not enough time, we could schedule this for next sprint, just let me know

**Comment by mbellotti** [comment]
This commit uses organization_show, which does have an include_packages option. Organization_list does not. Out of the box we cannot sort by package views/downloads without access to the package dict There are a couple of options from here:

1) Iterate through every single org and call organization_show to get a list of datasets to calculate the popularity score for each organization. **NOT RECOMMENDED**

2) Change organization_list and add a include_packages option. Viable but not really recommended because the dictionary it returns will be massive.

3) Add an extra to organizations that tracks the number of views (either of the organization itself or of its datasets) and create hooks that update this field. This is the best option I think, but it is more work than the other two.

Unless @alexandru-m-g has any other suggestions?

**Comment by cjhendrix** [comment]
Unless there are other ideas, I'd suggest you and @danmihaila estimate the work required for option 3 and discuss with @amcguire62

**Comment by cjhendrix** [comment]
Actually, after a discussion on the SPAR, we'll close this for now and leave it as is (sorting by number of public datasets).  If we are still interested in exploring some other measure of popularity, we can come up with an estimate for option 3 as described by Marianne above.
