### ISSUE TITLE
Share button defaulting to long URLs

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3542]
Apparently we have exceeded our quota on shortened URLs and are failing (gracefully!!) back to the long URL.  No one is complaining about this, so I think we ignore for now, but I just wanted to document it since it came up recently due to an unrelated bug in the share function.    **If** we decide to fix it, @alexandru-m-g  thought we may be able to get a much higher quota by passing an API key to the URL shortening URL.

**Comment by mbellotti** [comment]
Sorry I keep forgetting to write up my thoughts on this. Yes, Alex is right. The Google URL shortener api can be used without a key, but the limits are much stricter. Register HDX with Google and add a key to the request will give us 1,000,000 requests per day. [ @cjhendrix it looks like we need you to do this, since we do not have access to the HDX google account ] Since we store old requests, this should be plenty.

If we still need more requests, the only other option is to build our own shortening service. There's no free service that will allow you infinite requests.

**Comment by mbellotti** [comment]
Also I can fix this as soon as I have the key :)

**Comment by alexandru-m-g** [comment]
Our own shortening service - that's interesting. Could be a possible solution ( not the only one ) to be able to count the users that clicked on shared resource download links ( related to #3680 )

**Comment by mbellotti** [comment]
Can we close this?

**Comment by danmihaila** [comment]
Is it done?

**Comment by mbellotti** [comment]
There is nothing to do unless CJ wants to generate an API key.

**Comment by danmihaila** [comment]
did you discuss with @cjhendrix about this?

**Comment by mbellotti** [comment]
There's really nothing to discuss, it's a research issue. I researched the
answer to his question and pinged him with possible actions. The actual
issue itself says he plans on just ignoring the issue for now.

**Comment by cjhendrix** [comment]
@mbellotti  What kind of API key do we need?  Choose from Server, Browser, iOS, Android.    I'm guessing it's Server, but wanted to confirm.

**Comment by mbellotti** [comment]
Yup :) You're right. Send key to me over slack DM when you have it?

**Comment by danmihaila** [comment]
assigned to @aalecs to investigate why when not logged in the popup is not well aligned.
