### ISSUE TITLE
Popular/downloads/view flame icons

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3684]
This is related to #3651, #3680 and another already closed issue.
- [ ] We need to understand how ckan is tracking dataset page views and resources download. 
- [ ] We need to understand how to display page views and resource download. After we know this, we can talk to @yumiendo  and @luiscape how to display
- [ ] What is the difference between direct access for download or click in browser
- [ ] How often is triggered the update of download numbers and refreshed
  ![screen shot 2015-10-08 at 12 47 28](https://cloud.githubusercontent.com/assets/3865844/10363127/512503b2-6dbb-11e5-87ef-771379304b3b.png)
  ![screen shot 2015-10-08 at 12 47 26](https://cloud.githubusercontent.com/assets/3865844/10363126/51239d7e-6dbb-11e5-844a-718741748e9b.png)
  ![screen shot 2015-10-08 at 12 47 23](https://cloud.githubusercontent.com/assets/3865844/10363125/51232cd6-6dbb-11e5-9a06-3182033535ef.png)
  ![screen shot 2015-10-08 at 12 47 14](https://cloud.githubusercontent.com/assets/3865844/10363124/5121835e-6dbb-11e5-95db-6a653b89a756.png)

**Comment by mbellotti** [comment]
Okay so tracking.js sends an ajax POST request back to CKAN in two different situations:
- When the script is initialized (ie - on page load) This therefore tracks the number of "views"
- When the download button is clicked, thereby tracking the number of downloads.

Therefore dataset views does not equal the total of all resource views within the dataset because they are usually tracking different things. Dataset views are pageviews, resource views are usually downloads (unless the resource is preview-able in which case both stats will be tracked separately.

The request gets directed to https://github.com/ckan/ckan/blob/master/ckan/config/middleware.py#L330 where CKAN inserts these records into table tracking_raw.

When running paster, CKAN takes the data in tracking_raw and creates summaries in tracking_summary. This is what CKAN fetches when you load a dataset page.

Accessing a file through CKAN's API will not be tracked. See discussion here http://stackoverflow.com/questions/28421973/does-ckan-log-the-url-click and here https://github.com/ckan/ideas-and-roadmap/issues/72

Forcing consistency on the dataset page itself is easy. The problem is the search results. For the time being we've just removed the number there (very few people seemed to know it was there anyway)

**Comment by luiscape** [comment]
@mbellotti very informative!
