### ISSUE TITLE
New Contribute Flow: Google Drive/Dropbox/API-URL

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3889]
- [x] research how to use Google Drive as selecting file tool
- [x] research how to use Dropbox as selecting file tool
- [x] implement Google Drive to select a file
- [x] implement Dropbox to select a file
- [x] implement API/URL feature - allow user to add an API/URL as resource (Yumi’s input still needed)

Things to investigate:
- check multiple selection for files
- how to add a link to the file (from google drive/dropbox)
- how to upload a selected file (from google drive/dropbox) into ckan - it might be a later requirement - not high priority

**Comment by brew** [comment]
Some remarks about the Dropbox/Google Drive integration:
- URLs selected with the Dropbox/Google Drive APIs will pre-fill the name field, but only if it's empty. Perhaps for the cloud resources, this should always pre-fill, regardless if it's empty?
- The link to Dropbox items is for the 'preview' page. Direct links expire after 4 hours so aren't appropriate for our use. There's a link from the preview page to download the resource though.
- We're relying on the user to ensure cloud resources they select are publicly accessible.

**Comment by alexandru-m-g** [comment]
@brew as you said, the application needs to be registered with Google/Dropbox in order for this to work. Could you explain a bit about how this is setup in HDX and what we should do on developer machines for this to work (like do we each need to create an account for this) ?

Maybe we should give some notice to the user about the fact that he is responsible to make sure that the shared resource is already public in the respective service ( Google or Dropbox ). Is there an option/feature for the user to make it public while selecting the file ?

**Comment by brew** [comment]
HDX has apps registered for both Dropbox and Google tied to accounts owned by HDX with each service.

The Google app (_HDX Resource URL Picker_) requires a **Browser API key**, and an **oAuth client ID**. Both credentials are available from the HDX Google account page here: https://console.developers.google.com/apis/credentials. For the app to work from a particular domain, the domain needs to be added to the section 'Accept requests from these HTTP referrers (web sites)' for the Browser API key, and to the 'Authorized JavaScript origins' section for the oAuth client ID. Currently, I've added domains for my local development IP and the production HDX website. If other developers want to test this feature locally they will need to add their own development domain.

For Dropbox, the app is available from here: https://www.dropbox.com/developers/apps, called _HDX URL Chooser_. Again, allowed domains can be added to the section **Chooser/Saver domains**.

**Comment by brew** [comment]
As far as I can see, there's no option for the user to make a file public from the Picker/Chooser (they are both very simple interfaces). I also can't see a way to filter the results to only show publicly accessible files.

**Comment by alexandru-m-g** [comment]
After discussing with @yumiendo  to add more information for the user about how sharing via Google Drive and Dropbox works (related to permissions). There will be a short info on hover and more detailed text on the left side of the resources. The text itself will be provided by Yumi

**Comment by alexandru-m-g** [comment]
From @yumiendo 

## left column

#### Adding files via Dropbox:

Please be advised that by adding files via dropbox, file sharing setting turns on automatically and becomes viewable by anyone with the link.  

#### Adding files via Google Drive:

In order to add your file(s) from Google Drive, sharing settings of file(s) has to be on so your file(s) becomes viewable on HDX. 
For instructions on how to change, please visit our FAQ. “

## hover text

#### for google drive:

“In order to add files via google drive, sharing settings has to be on. 

#### for dropbox:

"By adding files via dropbox, file sharing setting turns on automatically and becomes viewable by anyone with the link"

## FAQ:

to be added under **“Sharing Data”**

"How do I share files from Google Drive?”
You can now connect to Google Drive and select files directly from “Add Data”. 
Unless your file(s) is already publicly accessible or shared with anyone with the link, the following steps are necessary to make your files viewable by others on HDX. 

How to turn on sharing settings on Google Drive:
1. Go to Google Drive. 
2. Right click on file(s) you want to share on HDX and select “Share”.
3. In "Sharing with others" window, click on “Advanced” in the bottom right corner.
4. In "Sharing settings” window, click on “change” under “Who has access”.
5. In the next screen, select "On -Public on the web" or "On - anyone with the link” and make sure "Access:Anyone (no sign-in required)” is set to “can view"

**Comment by alexandru-m-g** [comment]
Added the documentation.
