### ISSUE TITLE
New Contribute Flow: saving dataset flow

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3936]
After saving a dataset - redirect to the next screen (dataset view) and close the modal.
In the next iteration we will add also the review screen.

**Comment by alexandru-m-g** [comment]
Changes to the dataset saving process:

After discussing with @yumiendo the following changes should be done to the process of saving changes to a dataset:
-  Generally, there shouldn't be any changes persisted until the user clicks on the submit button at the bottom of the page
-  More precisely:
  -  new files that are added to a dataset ( via drag&drop or via the browse button ) **should NOT be uploaded automatically** to the underlying dataset
  -  changes to existing resources ( when editing a dataset ) will not be saved until the user clicks the submit button
-  Since submitting the data might take a long time if the files are large, when clicking the submit button a modal showing a text like _"Saving....this might take a few moments"_ should appear ( similar to how it appears when a visualization is loading on the wfp page )
  -  For a second iteration we should think about a way of estimating the time needed to submit the form ( together with all the files )

**Comment by alexandru-m-g** [comment]
Still TODO in Sprint 76: validating resource metadata before save.
