### ISSUE TITLE
Json preview not working

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4015]
based on email, json preview doesn't seem to work.
I also tried to test on staging: https://test-data.hdx.rwlabs.org/dataset/emergency-interventions-funded-using-the-emergency-envelope/resource/35705b22-9d10-42c1-9c0b-6f196742f495

**Comment by alexandru-m-g** [comment]
1) There is an issue with the configuration of the server that hosts the json file (data.waterpointdata.org). It doesn't support the "HEAD" HTTP command which CKAN ( actually one of it's libraries ) uses :

```
alex@alexlaptop:~> curl -I https://data.waterpointdata.org/resource/amwk-dedf.json
HTTP/1.1 400 Bad Request
Server: nginx
Date: Wed, 20 Jan 2016 16:31:13 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
X-Error-Code: invalid_request
X-Error-Message: HEAD is not supported
X-Socrata-Region: production
Age: 0
```

@amcguire62 @danmihaila 
Can the owner of the server change this ?
Should we try to modify/rewrite the CKAN proxy functionality to deal with such cases ?

2) There seems to also be an issue with the redirection from HTTP to HTTPS, like here https://data.hdx.rwlabs.org/dataset/madagascar-settlements/resource/56ac7739-1aa9-4eb0-9edd-29aca9252c12. @teodorescuserban is already looking into this

3) Why Dan's link ( from the ticket description above) is giving an error, that is another story. Either it's related to (2) OR Since the file is big, the proxy should actually give a "Content is too large" error that for some reason we don't see. There's also the question about why the proxy is used in the first place, since Dan's resource is actually local to the server. Let me know if I should investigate this further.
