### ISSUE TITLE
New Contribute Flow: Add mandatory red stars for fields

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4051]
can we add \* to mandatory fields under resources so its obvious. 
![screen shot 2016-02-05 at 17 01 54](https://cloud.githubusercontent.com/assets/3865844/12849800/38a7a614-cc2a-11e5-8fb5-7d6fdb34ae76.png)

**Comment by alexandru-m-g** [comment]
@danmihaila 
This is actually a bit more tricky then it seems. I tried to get it working by using just placeholders and CSS but got stuck because:
1.  Styling placeholders is a non-stadard feature in browsers that the documentation advises against ( since it might have different results for different users using different browsers ) : https://developer.mozilla.org/en/docs/Web/CSS/::-moz-placeholder
2.  `<input>` doesn't support the `:after` pseudo-class in firefox and the same seems to be true about the placeholder inside the input: http://stackoverflow.com/questions/24069830/2-colors-in-one-placeholder-of-input-field/24076889#24076889

We should probably replace the placeholders with `<label>` if we want to achieve this. Postponing this for now as it is low priority

**Comment by yumiendo** [comment]
@alexandru-m-g is adding a gray \* also hard to do? i can be ok with gray ones if thats easier to do.

**Comment by alexandru-m-g** [comment]
ok, gray is easy
