### ISSUE TITLE
New Contribute Flow: File format dropdown under ‘resource’ has a bit of delay

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4054]
When you start typing file format - it has a delay (and I thought predictive dropdown wasnt working) is there a way to show options quicker?
After a discussion with @yumiendo : can a search icon change to loading gif? it can be same one as the one we used on dataset page under meta data > "Visibility: Private - make it public"
![screen shot 2016-02-09 at 14 59 14](https://cloud.githubusercontent.com/assets/3865844/12916799/be12d1dc-cf3d-11e5-8e21-27fe9f0128c9.png)

**Comment by aalecs** [comment]
@danmihaila 
There isn't a way to show them quicker because the options are generated server-side. Maybe they can be cached a bit? @alexandru-m-g 
The current select2 search has a loading spinner that is replacing the search icon while it's getting the response from the back-end. Is it not working for you? I checked Safari/Chrome/Firefox and in all of them it's working :)
