### ISSUE TITLE
Wrong number of datasets displayed

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#414]
Login as hdx
search "test"
it says 5 datasets, but there are displayed only 3.
Check screenshot
![screen shot 2014-05-27 at 15 16 37](https://cloud.githubusercontent.com/assets/3865844/3091180/f2f67862-e598-11e3-92f2-ff3a8feeb543.png)

**Comment by kratos1308** [comment]
Hi everyOne, sorry to bring it back but i have this problem of wrong number of dataset.
First time everything was good and then i've had the idea to clean my database in order to remove the test datasets and start from empty db, couldn't be able to do that, i create a second database and delete the first one. 
When i init this new db and run ckan there were 3 datasets ( the one i've just created and 2 of the test datasets of the first db already deleted.
I checked the table but everything seems okey.

Do you have any idea please ?
Thanks for your time.
