### ISSUE TITLE
Indicator csv and txt files not previewing

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4180]
![image](https://cloud.githubusercontent.com/assets/1654485/15207172/9e392426-1824-11e6-8cad-70b1301c109f.png)

**Comment by alexandru-m-g** [comment]
@cjhendrix Text files I was able to preview: https://data.humdata.org/dataset/yem_baseline_data/resource/9fe2698c-87b5-4d66-bba5-5f22f8729e59

@teodorescuserban Is it possible that the switch to the new domain is causing dataproxy some problems. Maybe because links to manage.hdx.rwlabs.org are also redirected ?

**Comment by alexandru-m-g** [comment]
This was fixed by @teodorescuserban on production. There was a problem with the name resolution for our old CPS domain (manage.hdx.rwlabs.org).

Not sure if there are some modifications that still need to be done on the docker configuration files so I'm assigning this to Serban. If there's nothing else to be done, please close.

**Comment by teodorescuserban** [comment]
Really fixed now. Will propagate the changes to docker images this week.
