### ISSUE TITLE
WHS: Homepage - search not working on mobile

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4188]
When searching on mobile, click on one option is doing nothing.
![screen shot 2016-05-16 at 15 13 19](https://cloud.githubusercontent.com/assets/3865844/15289153/dc2970cc-1b78-11e6-88fc-078291b933d2.png)

**Comment by baripembo** [comment]
@danmihaila @aalecs It appears that the mobile search is not working because it does not like that there are two div's with id="search-ahead". One in the desktop nav and one in the mobile nav. I don't have access to the js that is initializing this search ahead functionality -- would it be possible to rename one of the divs and target both for the search ahead functionality?

I would also add this style to the (max-width: 767px) media query:
 body.home .search-ahead {
    width: 120%;
  }

Let me know if any of this doesn't make sense!

**Comment by aalecs** [comment]
Fixed + added style for small layouts
